version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nestjs